# arxivの学問領域の指定
subject: 'q-fin.* OR stat.*'

# 検索キーワード
keywords:
    pairs trading: 5
    pairs: 4
    pair: 4
    arbitrage: 3
    factor: 3
    risk: 3
    finance: 2
    kalman: 4
    time-series: 2
    cointegration: 4
    portfolio: 4
    HFT: 1
    
# 通知の閾値
score_threshold: 0
